apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r33
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r1
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.2.0-debian-12-r0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 17.2.0
    created: "2024-11-25T07:20:02.872114924+05:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: a6cc6189b9d506d13f6b6873d30003d46c2623697944ffaf0c8eb49bdac6673f
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-16.2.2.tgz
    version: 16.2.2
  redis:
  - annotations:
      category: Database
      images: |
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.30.2-debian-12-r2
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r24
        - name: redis
          image: docker.io/bitnami/redis:7.2.5-debian-12-r2
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.61.0-debian-12-r2
        - name: redis-sentinel
          image: docker.io/bitnami/redis-sentinel:7.2.5-debian-12-r2
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 7.2.5
    created: "2024-11-25T07:20:02.879595442+05:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 4389f91f8ddabe85b0b2b2d38492bb3c07ba8dec93498c0e5ddc7ca675aa6571
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - charts/redis-19.6.2.tgz
    version: 19.6.2
  sagawise:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2024-11-25T07:20:02.865634116+05:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.2.2
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 19.6.2
    description: A Helm chart for Kubernetes
    digest: 1ed3d20843082ac941784bb80eeaac9662a9a904ec7c7de26949a7aae9764b47
    name: sagawise
    type: application
    urls:
    - sagawise-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-25T07:20:02.829571569+05:00"
