apiVersion: v2
appVersion: v0.1.1
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.2.3
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.3.0
name: sagawise
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
